[package]
name = "dh"
version = "0.1.0"
authors = ["Alex Xiong <alex.xiong.tech@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = { version = "^0.4", features = ["rand"] }
rand = "^0.8"
