[package]
name = "challenges"
version = "0.1.0"
authors = ["Alex Xiong <alex.xiong.tech@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
openssl-sys = "0.9"
openssl = "0.10"
serde_json = "1.0"
anyhow = "1.0"

[dependencies.xor]
path = "../xor"

[dependencies.encoding]
path = "../encoding"

[dependencies.cryptanalysis]
path = "../cryptanalysis"

[dependencies.cipher]
path = "../cipher"

[dependencies.prng]
path = "../prng"
